[package]
name = "spin-config"
version = "0.1.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
spin-appconfig = { path = "../appconfig" }